name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Lint the code
        run: flake8 --ignore=E501 src/model.py

  testing:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: python src/model.py

  deployment:
    runs-on: macos-latest
    needs: [linting, testing]
    steps:
      - name: Echo Deployment
        run: echo "Model deployment successful!"

